<a href="https://colab.research.google.com/github/royarkaofficial/DataOps-Lab2-24th-Dec-2024/blob/main/Copy_of_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Array operations

Importing the NumPy Library

In [1]:
import numpy
import numpy as np

In [2]:
a = [7,8,9]
print(a*3)

[7, 8, 9, 7, 8, 9, 7, 8, 9]


Creating the Arrays

In [3]:
import numpy as np
arr = np.array([1,2,3])
print(arr*3)

[3 6 9]


In [6]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [7]:
arr3 = np.array(
    [
        [[1,2,3],[4,5,6]],
         [[7,8,9],[10,11,12]]
    ])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Creating array with default values

In [8]:
arr_zero = np.zeros((2,3))
print(arr_zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
arr_one = np.ones((4,6))
print(arr_one)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [17]:
array_random = np.random.random((3,2))
print(array_random)

[[0.66426863 0.28874922]
 [0.03666902 0.09821895]
 [0.93003454 0.24976449]]


Finding Dimensions

In [18]:
print(arr)
print(arr2)
print(arr3)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [19]:
print(arr.ndim)
print(arr2.ndim)
print(arr2.ndim)

1
2
2


In [20]:
print(arr.shape)
print(arr2.shape)
print(arr3.shape)

(3,)
(2, 3)
(2, 2, 3)


In [21]:
print(arr.size)
print(arr2.size)
print(arr3.size)

3
6
12


Array Operations

Basic Arithmetic operations

In [22]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(a1+a2-a1)
print(a1-a2)
print(a1*a2)
print(a1/a2)

[4 5 6]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Basic Mathematical functions

In [23]:
arr = np.array([[1,2,3],[4,5,6]])
print(np.sum(arr))

21


In [24]:
print(np.sum(arr,axis=0))

[5 7 9]


In [25]:
print(np.sum(arr,axis=1))

[ 6 15]


In [26]:
arr = np.array([1,2,3,4,5,6,7,8,9,20])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

6.5
5.5
5.123475382979799


In [27]:
print(np.min(arr))
print(np.max(arr))

1
20


In [28]:
print(np.prod(arr))

7257600


In [29]:
arr = np.array([1.2,3.5,5.8,6.7])
print(np.round(arr))

[1. 4. 6. 7.]


In [30]:
print(np.floor(arr))

[1. 3. 5. 6.]


In [31]:
print(np.ceil(arr))

[2. 4. 6. 7.]


Indexing and Slicing

In [32]:
arr = np.array([1,2,3,4,5,6])
print(arr[0])
print(arr[-1])

1
6


In [33]:
arr2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(arr2d.shape)

(3, 3)


In [34]:
print(arr2d[0,1])

2


In [35]:
print(arr2d[2,0])

7


In [36]:
print(arr2d[1,-1])

6


Slicing

array[start:stop:step]

In [37]:
abc = np.array([0,1,2,3,4,5,6,7,8,9,10])
print(abc[0:5])

[0 1 2 3 4]


In [40]:
print(abc[1:6:2])

[1 3 5]


In [41]:
print(abc[:5])
print(abc[5:])

[0 1 2 3 4]
[ 5  6  7  8  9 10]


In [42]:
print(abc[-5:])

[ 6  7  8  9 10]


In [43]:
arr2d = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])
print(arr2d.shape)

(4, 4)


In [44]:
print(arr2d[0:4,2:3])

[[ 3]
 [ 7]
 [11]
 [15]]



Reshaping

In [45]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr.shape)

(10,)


In [46]:
re_arr = arr.reshape(1,10)
print(re_arr)

[[ 1  2  3  4  5  6  7  8  9 10]]


In [47]:
print(re_arr.shape)

(1, 10)


Concatinating

In [48]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.concatenate((arr1,arr2)))

[1 2 3 4 5 6]


Spliting

In [49]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


Broadcasting

In [50]:
arr = np.array([1,2,3])
print(arr*3)

[3 6 9]


Random module

In [51]:
import numpy as np
arr = np.random.rand(3,2)
print(arr)

[[0.16418365 0.90918853]
 [0.55469803 0.77397278]
 [0.00442346 0.83596721]]


In [52]:
arr = np.random.randint(1,101,size=(100,200))
print(arr)

[[33 81 46 ... 35 95 29]
 [23 77 55 ... 54 59 19]
 [20 93 60 ... 60  2 37]
 ...
 [57 75 11 ... 85 47  7]
 [ 3  3 89 ... 98 36 50]
 [92 52 52 ... 70 33 24]]


In [53]:
arr = np.random.randn(4,4)
print(arr)

[[ 1.69849489  1.62663218  0.71629924  1.29125742]
 [ 0.73327977  1.08812003 -0.95385077 -0.73222463]
 [-0.86041012  0.3570895   0.03185714 -0.09247648]
 [-0.3770849   1.50136825 -0.86749415 -0.86180149]]


In [54]:
arr = np.random.choice([1,2,3,4,5,6] , size = (3,3))
print(arr)

[[5 6 5]
 [2 6 1]
 [4 1 5]]


In [58]:
arr = np.array([1,2,3,4,5,6])
np.random.shuffle(arr)
print(arr)

[5 6 1 3 2 4]
