<a href="https://colab.research.google.com/github/royarkaofficial/DataOps-Lab2-24th-Dec-2024/blob/main/Copy_of_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Array operations

Importing the NumPy Library

In [2]:
import numpy
import numpy as np

In [ ]:
a = [7,8,9]
print(a*3)

[7, 8, 9, 7, 8, 9, 7, 8, 9]


Creating the Arrays

In [ ]:
import numpy as np
arr = np.array([1,2,3])
print(arr*3)

[3 6 9]


In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr3 = np.array(
    [
        [[1,2,3],[4,5,6]],
         [[7,8,9],[10,11,12]]
    ])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Creating array with default values

In [3]:
arr_zero = np.zeros([2,3])
print(arr_zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
arr_one = np.ones((4,6))
print(arr_one)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
array_random = np.random.random((3,2))
print(array_random)

[[0.66426863 0.28874922]
 [0.03666902 0.09821895]
 [0.93003454 0.24976449]]


Finding Dimensions

In [ ]:
print(arr)
print(arr2)
print(arr3)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
print(arr.ndim)
print(arr2.ndim)
print(arr2.ndim)

1
2
2


In [ ]:
print(arr.shape)
print(arr2.shape)
print(arr3.shape)

(3,)
(2, 3)
(2, 2, 3)


In [ ]:
print(arr.size)
print(arr2.size)
print(arr3.size)

3
6
12


Array Operations

Basic Arithmetic operations

In [ ]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(a1+a2-a1)
print(a1-a2)
print(a1*a2)
print(a1/a2)

[4 5 6]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Basic Mathematical functions

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(np.sum(arr))

21


In [ ]:
print(np.sum(arr,axis=0))

[5 7 9]


In [ ]:
print(np.sum(arr,axis=1))

[ 6 15]


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,20])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

6.5
5.5
5.123475382979799


In [ ]:
print(np.min(arr))
print(np.max(arr))

1
20


In [ ]:
print(np.prod(arr))

7257600


In [ ]:
arr = np.array([1.2,3.5,5.8,6.7])
print(np.round(arr))

[1. 4. 6. 7.]


In [ ]:
print(np.floor(arr))

[1. 3. 5. 6.]


In [ ]:
print(np.ceil(arr))

[2. 4. 6. 7.]


Indexing and Slicing

In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr[0])
print(arr[-1])

1
6


In [ ]:
arr2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(arr2d.shape)

(3, 3)


In [ ]:
print(arr2d[0,1])

2


In [ ]:
print(arr2d[2,0])

7


In [ ]:
print(arr2d[1,-1])

6


Slicing

array[start:stop:step]

In [ ]:
abc = np.array([0,1,2,3,4,5,6,7,8,9,10])
print(abc[0:5])

[0 1 2 3 4]


In [ ]:
print(abc[1:6:2])

[1 3 5]


In [ ]:
print(abc[:5])
print(abc[5:])

[0 1 2 3 4]
[ 5  6  7  8  9 10]


In [ ]:
print(abc[-5:])

[ 6  7  8  9 10]


In [ ]:
arr2d = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])
print(arr2d.shape)

(4, 4)


In [ ]:
print(arr2d[0:4,2:3])

[[ 3]
 [ 7]
 [11]
 [15]]



Reshaping

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr.shape)

(10,)


In [11]:
re_arr = arr.reshape(1,10) # (10),(10,1)
print(re_arr)

[[ 1  2  3  4  5  6  7  8  9 10]]


In [12]:
print(re_arr.shape)

(1, 10)


Concatinating

In [13]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.concatenate((arr1,arr2)))

[1 2 3 4 5 6]


Spliting

In [14]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


Broadcasting

In [ ]:
arr = np.array([1,2,3])
print(arr*3)

[3 6 9]


Random module

In [15]:
import numpy as np
arr = np.random.rand(3,2)
print(arr)

[[0.7794139  0.23383199]
 [0.79074814 0.87642915]
 [0.81669233 0.34300609]]


In [17]:
arr = np.random.randint(1,101,size=(100,200))
print(arr)

[[ 68  50  91 ...  91  29  67]
 [ 95  39  72 ...  74  64 100]
 [  1  42  27 ...   3  17  68]
 ...
 [ 24  75  96 ...  25  64  93]
 [ 14  32  26 ...  28  71  60]
 [ 36  28  39 ...  98  71  17]]


In [22]:
arr = np.random.randn(4,4)
print(arr)

arr1 = np.random.uniform(2, 8, size=(4, 4))
print(arr1.astype(int))

[[ 0.85854089 -0.06056753 -0.14240043  0.16722024]
 [-0.43733865  0.76973358  0.27779799  1.2177104 ]
 [-0.3884075  -2.25622219  0.85331896  0.38114372]
 [ 0.78472035 -2.07032942  0.12824697 -1.00991185]]
[[6 2 2 6]
 [5 2 2 7]
 [6 6 6 6]
 [2 6 6 6]]


In [25]:
arr = np.random.choice([1,2,3,4,5,6] , size = (3,3))
print(arr)

[[1 1 3]
 [5 1 2]
 [4 4 6]]


In [27]:
arr = np.array([1,2,3,4,5,6])
np.random.shuffle(arr)
print(arr)

[4 5 2 1 3 6]
